/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2221221702_zeynepsude_yılmaz_bp2_proje;

import javax.swing.JFileChooser;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zeysu
 */
public class Admin_page extends javax.swing.JFrame {

    /**
     * Creates new form Admin_page
     */
    public Admin_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        list_customer = new javax.swing.JButton();
        remove_costumer = new javax.swing.JButton();
        export_costumer = new javax.swing.JButton();
        import_costumer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "AD", "SOYAD", "KULLANICI ADI", "MAİL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        list_customer.setText("MÜŞTERİLERİ LİSTELE");
        list_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_customerActionPerformed(evt);
            }
        });

        remove_costumer.setText("MÜŞTERİYİ SİL");
        remove_costumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_costumerActionPerformed(evt);
            }
        });

        export_costumer.setText("MÜŞTERİLERİ DIŞA AKTAR");
        export_costumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_costumerActionPerformed(evt);
            }
        });

        import_costumer.setText("MÜŞTERİLERİ İÇE AKTAR");
        import_costumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                import_costumerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remove_costumer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(export_costumer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(import_costumer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(list_customer)
                .addGap(30, 30, 30)
                .addComponent(remove_costumer)
                .addGap(18, 18, 18)
                .addComponent(export_costumer)
                .addGap(18, 18, 18)
                .addComponent(import_costumer))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_customerActionPerformed
        // Fetch data from the database and populate the jTable1 table
        DatabaseConnection dbConnection = new DatabaseConnection();
        List<User> users = dbConnection.getAllUsers();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear the existing table data

        for (User user : users) {
            model.addRow(new Object[]{user.getName(), user.getSurname(), user.getUsername(), user.getEmail()});
        }        // TODO add your handling code here:

    }//GEN-LAST:event_list_customerActionPerformed

    private void remove_costumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_costumerActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen silmek istediğiniz müşteriyi seçin.", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String username = jTable1.getValueAt(selectedRow, 2).toString(); // Kullanıcı adını al
        int confirm = JOptionPane.showConfirmDialog(this, "Seçili müşteriyi silmek istediğinize emin misiniz?", "Müşteri Sil", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Müşteriyi sil
            DatabaseConnection dbConnection = new DatabaseConnection();
            boolean success = dbConnection.deleteUser(username);
            if (success) {
                JOptionPane.showMessageDialog(this, "Müşteri başarıyla silindi.", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
                // Tabloyu güncelle
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(this, "Müşteri silinirken bir hata oluştu.", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_remove_costumerActionPerformed

    private void export_costumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_costumerActionPerformed
        // TODO add your handling code here:
        DatabaseConnection dbConnection = new DatabaseConnection();
        String filePath = "users_export.csv"; // Dosya yolunu belirleyin
        dbConnection.exportUsersToFile(filePath);
        JOptionPane.showMessageDialog(this, "Kullanıcılar başarıyla " + filePath + " dosyasına aktarıldı.", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_export_costumerActionPerformed

    private void import_costumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_import_costumerActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            DatabaseConnection dbConnection = new DatabaseConnection();
            List<User> users = dbConnection.readUsersFromFile(filePath);
            dbConnection.addMultipleUsers(users);
            JOptionPane.showMessageDialog(this, "Kullanıcılar başarıyla eklendi.");
        }
    }//GEN-LAST:event_import_costumerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton export_costumer;
    private javax.swing.JButton import_costumer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton list_customer;
    private javax.swing.JButton remove_costumer;
    // End of variables declaration//GEN-END:variables
}
